server:
  port: 2001
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password: sam
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
    application:
      name: PAYMENT-SERVICE

    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          default-zone: http://localhost:8761/eureka/
      instance:
        hostname: localhost