server:
  port: 1999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          routes:
            - id: ProductService
              uri: http://localhost://ProductService
              predicates:
                - Path=/product/**
            - id: Payment-service
              uri: http://localhost://payment-service
              predicates:
                - Path=/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

