spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multiple_database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# H2 Database (commented out, as per your original properties)
# h2:
#   console:
#     enabled: true
#     path: /h2-console

# Swagger configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui

server:
  port: 2001
