server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:XE
      username: narendra
      password: root


    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true